### ISSUE TITLE
Markdown link checker failing

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#141]
eg https://github.com/LukePrior/nbn-upgrade-map/actions/runs/5265270380/jobs/9517677253

Unfortunately this causes a markdown-link-checker error without showing what the problem is.

**Comment by lyricnz** [comment]
eg
```
❯ markdown-link-check README.md

FILE: README.md
/Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/link-check/lib/proto/http.js:40
        const url = encodeURI(decodeURIComponent(new URL(link, opts.baseUrl).toString()));
                              ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Object.check (/Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/link-check/lib/proto/http.js:40:31)
    at linkCheck (/Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/link-check/index.js:29:25)
    at /Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/index.js:119:9
    at /Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:246:13
    at replenish (/Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:446:21)
    at iterateeCallback (/Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:430:21)
    at /Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:327:20
const BlackHole = require('../BlackHole');
    at /Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:248:17
    at /Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/index.js:130:13
```

**Comment by lyricnz** [comment]
Found a defect on this https://github.com/tcort/markdown-link-check/issues/211

**Comment by lyricnz** [comment]
Modified the library to show the URL before error:
```
❯ markdown-link-check -p -v README.md

FILE: README.md
https://lukeprior.github.io/nbn-upgrade-map/
https://data.gov.au/dataset/ds-dga-19432f89-dc3a-4ef3-b943-5326ef1dbecc/details
Checking... [==                       ] 7%https://github.com/minus34/gnaf-loader
Checking... [====                     ] 15%https://minus34.com/opendata/georabble-intro-to-gnaf.pdf
Checking... [======                   ] 23%https://www.nbnco.com.au/residential/upgrades/more-fibre
Checking... [========                 ] 30%https://geojson.org/
Checking... [==========               ] 38%https://geojson.io/
Checking... [============             ] 46%https://img.shields.io/badge/dynamic/json?label=Suburb%20Progress%20vs%20Listed&query=%24.suburbs.listed.TOTAL.percent&url=https%3A%2F%2Fraw.githubusercontent.com%2FLukePrior%2Fnbn-upgrade-map%2Fmain%2Fresults%2Fprogress.json&suffix=%
/Users/simonroberts/.asdf/installs/nodejs/14.20.0/lib/node_modules/markdown-link-check/node_modules/link-check/lib/proto/http.js:41
        const url = encodeURI(decodeURIComponent(new URL(link, opts.baseUrl).toString()));
                              ^
```

In this case, the error is caused by a bare '%' sign which should be %25 for a percent sign.
