### ISSUE TITLE
KeyError: 'states' main.py

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#144]
See https://github.com/LukePrior/nbn-upgrade-map/actions/runs/5441631647/jobs/9895817175

Error:
```
Traceback (most recent call last):
  File "code/main.py", line 141, in <module>
    main()
  File "code/main.py", line 135, in main
    process_suburb(db, args.target_suburb, args.target_state, args.threads)
  File "code/main.py", line 85, in process_suburb
    suburb, state = select_suburb(target_suburb, target_state)
  File "code/main.py", line 29, in select_suburb
    for state, suburbs in suburb_list["states"].items():
KeyError: 'states'
```

Line in question: https://github.com/LukePrior/nbn-upgrade-map/blob/main/code/main.py#L29

The `get_all_suburbs` function in `suburbs.py` returns `geojson.read_json_file("results/all_suburbs.json")["states"]` therefore states doesn't exist on the result and we get the key error.

Removing the states key should fix the issue.

**Comment by LukePrior** [comment]
Pushed a hotfix will see if it fixes: https://github.com/LukePrior/nbn-upgrade-map/actions/runs/5441852894
